"""widen_ownership_percentage_precision

Revision ID: 7cb8dfd8dd81
Revises: 5e29132dc11c
Create Date: 2026-04-15 17:22:38.293567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb8dfd8dd81'
down_revision: Union[str, Sequence[str], None] = '5e29132dc11c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account_ownerships', 'ownership_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=7, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account_ownerships', 'ownership_percentage',
               existing_type=sa.Numeric(precision=7, scale=4),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
